# This tool gets "Tools" array from file loadToolsSettings.py and 
# generate loadTools.py file. 
# This should be run only once if you added new macro.
# There is no need to run it ad each workbench startup.

import loadToolsSettings

output = '''# This file has been automatically generated by the loadToolsAuto.py script. Don't change it here.

import FreeCAD, FreeCADGui
translate = FreeCAD.Qt.translate

def QT_TRANSLATE_NOOP(context, text):
    return text

import os, sys
import fakemodule
path = os.path.dirname(fakemodule.__file__)
iconPath = os.path.join(path, "Icons")

'''

# ######################################################################################################################
# Create Classes
# ######################################################################################################################

for tool in loadToolsSettings.Tools:

	output += f'''
# ######################################################################################################################
class {tool.name}():

	def GetResources(self):
		return {{"Pixmap"  : os.path.join(iconPath, "{tool.name}.{tool.icon}"),
				"MenuText": QT_TRANSLATE_NOOP("{tool.name}", "{tool.menuText}"),
				"ToolTip" : QT_TRANSLATE_NOOP("{tool.name}", "{tool.toolTip}"),
				"Accel"   : "" }}

	def Activated(self):

		import os, sys
		import fakemodule

		modulePath = sys.path
		
		module = "{tool.name}"
		
		path = os.path.dirname(fakemodule.__file__)
		path = os.path.join(path, "Tools")
		
		sys.path.append(path)

		if module in sys.modules:
			del sys.modules[module]

		__import__(module, globals(), locals(), [], 0)
		
		sys.path = modulePath

		return

	def IsActive(self):
		# not needed now, maybe in the future
		return True

FreeCADGui.addCommand("{tool.name}", {tool.name}())

	'''

# ######################################################################################################################
# Overwrite the file loadTools.py
# ######################################################################################################################

with open("loadTools.py", 'w') as file:
	file.write("%s" % output)
